Clase07
franeguerrero/CPFS2022II pull request #11
Opened 2022-08-07 04:12 UTC by franeguerrero

2022-08-16 14:33 UTC, SofiZ2001 requested changes

2022-08-16 14:33 UTC, SofiZ2001 commented on Clase 07/RegistroAutomotor/Vehiculo.ts
> +    private patente: string;
Las subclases no van a poder acceder a estos atributos a menos que esten `protected`

2022-08-16 14:33 UTC, SofiZ2001 commented on Clase 07/RegistroAutomotor/Auto.ts
> +
Debería tener alguna funcionalidad que lo diferencie de el resto de las subclases

2022-08-16 14:33 UTC, SofiZ2001 commented on Clase 07/RegistroAutomotor/Camion.ts
> +
Debería tener alguna funcionalidad que lo diferencie de el resto de las subclases

2022-08-16 14:33 UTC, SofiZ2001 commented on Clase 07/RegistroAutomotor/Moto.ts
> +
Debería tener alguna funcionalidad que lo diferencie de el resto de las subclases

2022-08-16 14:33 UTC, SofiZ2001 commented on Clase 07/telefono.ts
> +    private bateriaActual: number;
Las subclases no van a poder acceder a estos atributos a menos que esten protected

2022-08-24 02:12 UTC, SofiZ2001 approved these changes
LG2M

2022-09-26 13:43 UTC, JulianaDimeglio approved these changes
si resolves los conflicts LGTM

2022-10-10 16:41 UTC, merged